### ISSUE TITLE
Tiny update in the documentation for Windows users

### ISSUE THREAD

**Issue by sevenate** [logrusorgru/aurora#10]
On Windows 10 the new ANSI Terminal Control is turned OFF by default, so users will not see any colors in the output if they run console Go program by just double clicking it.

But this setting could be easily turned on by simple change in registry:

[HKEY_CURRENT_USER\Console]
"VirtualTerminalLevel"=dword:00000001

More details about this issue in the answer from Glenn Slayden here - [Windows console with ANSI colors handling](https://superuser.com/questions/413073/windows-console-with-ansi-colors-handling)

So maybe mentioning about this nuance somewhere in the project README.md will save some time for Windows users.

**Comment by logrusorgru** [comment]
Thanks. All important Windows and TTY references are now in README.
