### ISSUE TITLE
offer global disable?

### ISSUE THREAD

**Issue by XSAM** [logrusorgru/aurora#16]
Can we support disable global color? In some platforms (like Windows) not support ANSI color, and I have to disable the color feature.

Currently, I can use `aurora.NewAurora()` to new a global variable. But it would be painful since the code no longer simplify.

```
# Global variable
color.Aurora.Green()

# Package
aurora.Green()
```

**Comment by logrusorgru** [comment]
```go
package main

import (
	"fmt"
	"runtime"

	auroraPackage "github.com/logrusorgru/aurora"
)

var aurora auroraPacakge.Aurora

func init() {
	if runtime.GOOS() == "windows" {
		aurora = auroraPackage.NewAurora(false)
	} else {
		aurora = auroraPackage.NewAurora(true)
	}
}

func main() {
	fmt.Println(aurora.Green("Hello"))
}
```
What about?

**Comment by logrusorgru** [comment]
I am doing my best to prevent users manipulate a global state, or a background state. If you want to turn off something -- make it explicitly. Another users of your code will never know about a global state and "why all it doesn't work as expected", and "where is it configured". Etc, etc. For few imported packages, using the aurora, some can enable, some can disable a global state. Result is not easily predictable.

**Comment by logrusorgru** [comment]
Also, please check out https://github.com/logrusorgru/aurora/issues/2#issuecomment-299014211 this thread. There is a way to enable Windows colors.

**Comment by XSAM** [comment]
> For few imported packages, using the aurora, some can enable, some can disable a global state. Result is not easily predictable.

You are right. That would be confusing to the users. Thanks for the explanation.

**Comment by logrusorgru** [comment]
Version 4 adds a global state. Check it out.
