### ISSUE TITLE
disable colors with an env var

### ISSUE THREAD

**Issue by ORESoftware** [logrusorgru/aurora#17]
I saw this section on how to disable colors:

https://github.com/logrusorgru/aurora#enabledisable-colors

is there a way to disable colors with an env variable?

**Comment by ORESoftware** [comment]
I looked at the codebase and it seems pretty difficult to switch the default exported values with an env var :(

**Comment by logrusorgru** [comment]
> is there a way to disable colors with an env variable?

Yep. For example
```go
au = aurora.NewAurora(os.Getenv("COLORS") == "1")
```

**Comment by ORESoftware** [comment]
yeah I guess we can create our own little module and import it pretty easily, thanks
