### ISSUE TITLE
explanation of how code works :)

### ISSUE THREAD

**Issue by ORESoftware** [logrusorgru/aurora#18]
So I can import this library like so:

	import "github.com/logrusorgru/aurora"

and then use it like:

```golang
fmt.Println(aurora.Bold("foo"))
```

but I don't see Bold exported, I only see:

```golang
func (a aurora) Bold(arg interface{}) Value {

}

```
maybe I don't know enough about Go but how does that work?

**Comment by logrusorgru** [comment]
https://godoc.org/github.com/logrusorgru/aurora#Bold
