### ISSUE TITLE
Custom module requires manual setup

### ISSUE THREAD

**Issue by ORESoftware** [logrusorgru/aurora#19]
If I import the module as usual

```golang

import (
  "github.com/logrusorgru/aurora"
)

func init(){
  fmt.Println(aurora.Bold("foo"))
}
```

in other words I do not have to do:

```golang
func init(){
  fmt.Println(aurora.colors.Bold("foo"))
}
```

But if I want to turn off colors and use a custom package to do so:

```golang
package aw

import (
  "github.com/logrusorgru/aurora"
  "os"
)

var hasColors = os.Getenv("cm_no_colors") != "nope"
var x = aurora.NewAurora(hasColors)

var Red = x.Red         // manual
var Faint = x.Faint      // manual
var Bold = x.Bold       // manual .. etc

```

only using the local assigment of the method names can I get the same behavior. Now I can do:

```golang
import (
  "github.com/channelmeter/aurora-wrapper/aw"
  "os"
)

func init(){
  fmt.Println(aw.Bold("foo"))
}

```

so what I am trying to say is - is there some easier way to export all the methods instead of having to manually do it?

**Comment by logrusorgru** [comment]
```go
import (
     aurorapkg "github.com/logrusorgru/aurora"
)

var aurora aurorapkg.Aurora

// setup
```
That's all you need.

**Comment by logrusorgru** [comment]
Ref.: https://github.com/logrusorgru/aurora#enabledisable-colors

**Comment by logrusorgru** [comment]
And you can't the
```go
func init(){
  fmt.Println(aurora.colors.Bold("foo"))
}
```
anyway.

Please, learn Go basics at [tour.golang.org](https://tour.golang.org/welcome/1) first.

**Comment by logrusorgru** [comment]
Please, check out [Aurora interface](https://godoc.org/github.com/logrusorgru/aurora#Aurora) that is colorizer. The [NewAurora](https://godoc.org/github.com/logrusorgru/aurora#NewAurora) function returns a colorizer, with or without colors, depending on argument. The Aurora interface implements all required to use it as `aurora.Bold` etc. Other words,
```go
package main

import (
    "fmt"
    "github.com/logrusorgru/aurora"
)

func main() {
    fmt.Println(aurora.Bold("Bold"))
}
```
This example  uses package level functions. But here
```go
package main

import (
    "fmt"
    "os"
    aurorapkg "github.com/logrusorgru/aurora"
)

var aurora = aurorapkg.New(os.Getenv("cm_no_colors") != "nope")

func main() {
    fmt.Println(aurora.Bold("Bold"))
}
```
we are using the Aurora interface methods.

**Comment by logrusorgru** [comment]
> so what I am trying to say is - is there some easier way to export all the methods instead of having to manually do it?

What the hell. Just don't do it. It's totally wrong any side. Misuse, wrong approach. If you want to do something wrong, I will not help you. The aurora package is not designed to wrap it by another package. It contains all necessary to use it with or without colors. All necessary.

**Comment by logrusorgru** [comment]
Sir, do you have any questions?

**Comment by logrusorgru** [comment]
Closed due to age.

**Comment by logrusorgru** [comment]
So. Sorry, man. Finally, I understood your intention.

**Comment by logrusorgru** [comment]
But, I'm not sure it's good. Since, there are opinions against a global state, and there are opinions against dot imports.

**Comment by logrusorgru** [comment]
v4 have global state, check it out
