### ISSUE TITLE
Support for Windows cmd?

### ISSUE THREAD

**Issue by Equim-chan** [logrusorgru/aurora#2]
I tried to use it in my project. The code is like:
```go
log.Println(Cyan("Broken Pantsu"), Bold(VERSION))
```
but when I run it on my Windows cmd shell it prints:
```
00:39:45.419785 main.go:85: ←[36mBroken Pantsu←[0m ←[1mtest-build←[0m
```

GOARCH=amd64
GOOS=windows

**Comment by logrusorgru** [comment]
There are not a Windows support. It supports only ANSI-colors. ANSI-colors are escape codes like `\033[31m`, `\033[0m`, etc. For example `\033[36m` is cyan color.

There is [github.com/mattn/go-colorable](http://github.com/mattn/go-colorable) package that wraps windows output to print ANSI-colors correct. I'm not sure that it works. Here is a research of someone: [image](http://i.imgur.com/PBcyH5A.png).

If you use `log` package (not `fmt`) then you can use [SetOutput](https://godoc.org/log#SetOutput) method. For example
```go
package youPackage

import (
    "log"

    "github.com/mattn/go-colorable" // colorable
    "github.com/logrusorgru/aurora"
)

func init() {
    log.SetOutput(colorable.NewColorableStdout()) // or NewColorableStderr()
}

func main() {
   log.Print(aurora.Cyan("hey!"))
    // stuff
}

```
This way, output of `log`-functions will be handled by the `colorable` package and colorized correctly (not sure).
Feel free to ask if it is not clear enough.

---
godoc links:

- [colorable.NewColorableStdout](https://godoc.org/github.com/mattn/go-colorable#NewColorableStdout)

**Comment by Equim-chan** [comment]
I know that's ANSI color, but it just becomes weird when the same trick works fine in other languages.
For example in Nodejs,
```js
console.log('\x1b[36mCyan\x1b[0m');  // works
```
Tools from MinGW that support color also work well, like `ls --color` and `grep --color`.
Also, my shell is cmder actually, but it runs over cmd.

**Comment by logrusorgru** [comment]
Hm, I need reboot to explore the issue. I think that Nodejs has some internal workaround. A moment.

**Comment by Equim-chan** [comment]
I just checked the source code of [github.com/mattn/go-colorable](https://github.com/mattn/go-colorable); its functions are based on [importing kernel32.dll](https://github.com/mattn/go-colorable/blob/master/colorable_windows.go#L63) and the corresponding Windows APIs, which doesn't seem to be a graceful workaround but at least works.

**Comment by logrusorgru** [comment]
Windows 7 x64. First output uses the `colorable`. Second one don't use it. And nodejs output for example.
![screen](https://cs541602.userapi.com/c636531/v636531524/5e4af/NCjta546oi8.jpg)

**Comment by Equim-chan** [comment]
Thanks for the testing. One other question is, does this package replace the strings unconditionally? Does it detect the tty context?

**Comment by logrusorgru** [comment]
Yes, I think. Take a look https://github.com/mattn/go-colorable/blob/master/colorable_windows.go#L88. It uses `isatty` package

**Comment by Equim-chan** [comment]
Well, I mean in your aurora package.

**Comment by logrusorgru** [comment]
No, never.

**Comment by Equim-chan** [comment]
Hmm, that's not good when stdout is piped to a log file, which does not need colors.

**Comment by logrusorgru** [comment]
You can to use the `isatty` package with `aurora.NewAurora` (see README for example).  The `aurora` package uses another approach to turn on/off colors. This way, you can keep colors if you want (even output is a file).

---
- [isatty](https://github.com/mattn/go-isatty)
- [enable/disable colors](https://github.com/logrusorgru/aurora#enabledisable-colors)

**Comment by logrusorgru** [comment]
For example (the example works fine)
```go
package main

import (
	"log"
	"os"

	"github.com/logrusorgru/aurora"
	"github.com/mattn/go-colorable"
	"github.com/mattn/go-isatty"
)

// colorizer
var au aurora.Aurora

func init() {
	au = aurora.NewAurora(isatty.IsTerminal(os.Stdout.Fd())) // create colorizer
	log.SetOutput(colorable.NewColorableStdout())
}

func main() {
	log.Print(au.Cyan("hey!"))  // use colorizer
}
```

**Comment by logrusorgru** [comment]
Also. The colorizer has the same set of methods as the `aurora` packae. I.e. you can call it `aurora` instead of `au` to avoid renaming everywhere.
```go
package main

import (
	"log"
	"os"

	auroraPackage "github.com/logrusorgru/aurora"
	"github.com/mattn/go-colorable"
	"github.com/mattn/go-isatty"
)

var aurora auroraPackage.Aurora

func init() {
	aurora = auroraPackage.NewAurora(isatty.IsTerminal(os.Stdout.Fd()))
	log.SetOutput(colorable.NewColorableStdout())
}

func main() {
	log.Print(aurora.Cyan("hey!")) // aurora.Cyan as it was
}
```
**But**. Colors are package-level (BoldFg, BlueBg etc)

**Comment by logrusorgru** [comment]
> I just checked the source code of github.com/mattn/go-colorable; its functions are based on importing kernel32.dll and the corresponding Windows APIs, which doesn't seem to be a graceful workaround but at least works.

If you are worried about the 32, the `kernel32.dll` is for 32- and 64-bit systems too.

**Comment by logrusorgru** [comment]
About _"replace the strings unconditionally"_. There is some overhead, anyway. For example, if colors disabled `Cyan("string")` wraps the "string" with some internal struct to get Value interface instead of string. Thus, all overheads of `log.Print(Cyan("string"))` is `"string"` -> `interface{}(...)` -> `struct{...}` -> `fmt.Sprint(...)` -> the result used by log.Print. And steps that cost are: (1) conversion to `interface{}` (2) call of `fmt.Sprint`.

May be, the package is not best solution for high performance logs, if colors are switched off. The goal was usability. However, it can be faster then other packages, if colors are switched on.

Also, the package provided with good set of benchmarks.
