### ISSUE TITLE
Hyperlinks work in iterm2 but not in Intellij / Jetbrains terminals

### ISSUE THREAD

**Issue by amills-vibeirl** [logrusorgru/aurora#28]
this code for hyperlinks:
https://github.com/logrusorgru/aurora?tab=readme-ov-file#hyperlinks-default-colorizer-and-configurations

it works for me with iterm2 (on my Mac) but doesn't appear to work in my Intellij terminal.
Does it work in other terminals?

**Comment by amills-vibeirl** [comment]
I filed a ticket in Jetbrains/YouTrack here:
https://youtrack.jetbrains.com/issue/GO-16077/iterm2-displays-functioning-Hyperlink-but-Intellij-terminal-does-not

**Comment by logrusorgru** [comment]
There's the hyperlinks feature page. And something about it -- 
[supporting apps](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda#supporting-apps).

**Comment by logrusorgru** [comment]
Also, if a terminal emulator supports the feature, it may be disabled on your system.

**Comment by logrusorgru** [comment]
And no way to detect its availability from inside a terminal -- https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda#detecting-availability-of-the-feature .
