### ISSUE TITLE
Convert aurora.Value to string

### ISSUE THREAD

**Issue by MggMuggins** [logrusorgru/aurora#5]
Is there any way to do that? I'd like to use colored text for my prefixes for `log.Logger`, but it takes a string for the prefix.

**Comment by logrusorgru** [comment]
The [`Value`](https://godoc.org/github.com/logrusorgru/aurora#Value) interface includes [`fmt.Stringer`](https://godoc.org/fmt#Stringer). Short words, just call `String()` method.

**Comment by MggMuggins** [comment]
Thanks!
