### ISSUE TITLE
"%T" returns 'aurora.value'

### ISSUE THREAD

**Issue by kimfucious** [logrusorgru/aurora#6]
Hi,

cool package!

This command:

`fmt.Println(Sprintf(Green("We can see that the type of x is: %T"), Brown(x)))`

Returns:

`We can see that the type of x is: aurora.value`

I saw the workaround at in the readme for `%T` and `%p`, but the solution to print the type of x is still eluding me.

**Comment by logrusorgru** [comment]
https://github.com/logrusorgru/aurora#limitations

**Comment by logrusorgru** [comment]
Because `%T` and `%p` don't use [fmt.Formatter](https://godoc.org/fmt#Formatter) interface. Solution is, for example:
```go
fmt.Println(
    Sprintf(
        Green("We can see that the type of x is: %s"),
        Brown(fmt.Sprintf("%T", val),
    ),
)
```

**Comment by logrusorgru** [comment]
Or

```go
func typeOf(val interface{}) string {
    return fmt.Sprintf("%T", val)
}

// and

fmt.Println(Sprintf(Green("We can see that the type of x is: %s"), Brown(typeOf(x))))
```

**Comment by logrusorgru** [comment]
Also, the `fmt.Sprintf("%T", val)` is equal to `reflect.TypeOf(val).String()`. Thus the `typeOf` function above can be replaced with this one

```go
func typeOf(val interface{}) string {
    return reflect.TypeOf(val).String()
}
```

**Comment by logrusorgru** [comment]
Or, adding color inside the `typeOf` function

```go
func typeOf(val interface{}) string {
    return Brown(reflect.TypeOf(val).String()).String()
}

fmt.Println(Sprintf(Green("We can see that the type of x is: %s"), typeOf(x)))
```

**Comment by logrusorgru** [comment]
Thus, in a middle case `fmt.Sprintf("%T", val)` is better, because it's universal.
