### ISSUE TITLE
Backward compatibility

### ISSUE THREAD

**Issue by logrusorgru** [logrusorgru/aurora#8]
The v1.1 should be backward compatible with previous Aurora implementation. Please, let me know if the v1.1 breaks something.

**Comment by WGH-** [comment]
```
cannot use aurora.NewAurora(false).Gray (type func(uint8, interface {}) aurora.Value) as type func(interface {}) aurora.Value in assignment
```

**Comment by logrusorgru** [comment]
Hello, @WGH- , I've renamed v1.1 to v2.0. For now v1.0 is old (initial) version of the Aurora. Please, use
```go
"gopkg.in/logrusorgru/aurora.v1"
```
import path.

[GoDoc documentation](https://godoc.org/gopkg.in/logrusorgru/aurora.v1#Aurora).

**Comment by ryanavella** [comment]
Hi @logrusorgru, regarding @WGH-'s example, do you plan to document changes to the API? For example, BgGray now requires 2 arguments instead of 1.

**Comment by logrusorgru** [comment]
Hello, @ryanavella, please take a look at this paragraph: [Grayscale](https://github.com/logrusorgru/aurora#grayscale). A `Gray` and a `BgGray` method require gray color index (from 0 to 23 inclusive) and value to make it gray. There is [GoDoc](https://godoc.org/github.com/logrusorgru/aurora) documentations. Zero is black, 23 is white.

If a `Gray` or `BgGray` receive gray color out of the [0; 23] range, then nearest valid value used instead.

The `Gray` and `BgGray` methods are the same as `Index` and `BgIndex` where [0; 23] becomes [232; 255]. It's just [8-bit ANSI colors](https://en.wikipedia.org/wiki/ANSI_escape_code#8-bit).

Also, there is [CHANGELOG.md](https://github.com/logrusorgru/aurora/blob/master/CHANGELOG.md)

---

Previous `Gray` and `BgGray` methods are now called `White` and `BgWhite` following specification. Also, `Brown` and `BgBrown` is now `Yellow` and `BgYellow`. There are `Brown` and `BgBrown` but they are marked as deprecated.

**Comment by logrusorgru** [comment]
> If a Gray or BgGray receive gray color out of the [0; 23] range, then nearest valid value used instead.

Going to change it and introduce `GrayScale` and `BgGrayScale`. To make method names a bit intuitive.

Ref.: https://github.com/logrusorgru/aurora/issues/15

**Comment by logrusorgru** [comment]
Seems, we need the [gorename tool working](https://github.com/golang/go/issues/24661) with go modules, to make the changes.

**Comment by logrusorgru** [comment]
License has changed from the WTFPL to the Unlicense due to pkg.go.dev restriction. I hope no one is against it.
